package com.psu.exshell.Application;

public enum Mode {
    CREATE,
    UPDATE,
	CREATE_PREMISE_FACT,
	CREATE_CONCLUSION_FACT,
	UNDEFINED_INFERRER_STATE,
	GOAL_INFERRED,
	NEED_QUESTION,
	GOAL_NOT_INFERABLE,
	FACT_TRUE,
	FACT_FALSE,
	FACT_UNKNOWN;
}
